FROM ghcr.io/bcachet/containers/dev:latest AS dev
USER root
RUN <<EOF
dnf install -y \
  ansible \
  ansible-collection-containers-podman \
  --nodocs --setopt install_weak_deps=False
dnf clean all -y
EOF

USER bertrand
CMD ["/bin/bash"]
