FROM ghcr.io/bcachet/containers/dev:latest

RUN curl -LsSf https://astral.sh/uv/install.sh | env UV_INSTALL_DIR="/usr/local/bin" INSTALLER_NO_MODIFY_PATH=1 sh

RUN dnf install -y \
            python3 \
            python3-pip \
        --nodocs --setopt install_weak_deps=False \
    && dnf clean all -y

RUN pip3 \
        install \
            black \
            pep8
