FROM registry.fedoraproject.org/fedora-toolbox:40

RUN dnf install -y \
            curl \
            git \
            direnv \
            eza \
            fd-find \
            file \
            fzf \
            jq \
            just \
            neovim \
            opensc \
            openssh-clients \
            procps-ng \
            ripgrep \
            yq \
        --nodocs --setopt install_weak_deps=False \
    && dnf clean all -y

RUN dnf groupinstall -y 'Development Tools' \
        --nodocs --setopt install_weak_deps=False \
    && dnf clean all -y

# Install final user
RUN useradd -m -s /bin/bash bertrand \
&& echo 'bertrand ALL=(ALL) NOPASSWD:ALL' >>/etc/sudoers
USER bertrand

# Install Brew
RUN curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | bash
ENV PATH=$PATH:/home/linuxbrew/.linuxbrew/bin/

RUN brew \
        install \
            bottom \
            chezmoi \
            lazygit \
            starship \
    || true

