FROM ghcr.io/bcachet/containers/dev:latest

RUN brew install \
        clojure \
        clojure-lsp \
        borkdude/brew/babashka \
        leiningen \
    || true

RUN mkdir -p ${HOME}/.m2

VOLUME [ "${HOME}/.m2/" ]