FROM ghcr.io/bcachet/containers/dev:latest

RUN sudo dnf install -y \
            python3 \
            python3-pip \
        --nodocs --setopt install_weak_deps=False \
    && sudo dnf clean all -y

RUN pip3 \
        install \
            black \
            pep8 \
            flake8

RUN curl -LsSf https://astral.sh/uv/install.sh | sh
