FROM ghcr.io/bcachet/containers/dev:latest
USER root

RUN dnf install -y \
            bcc \
            bpftrace \
            iproute \
            nicstat \
            numactl \
            sysprof \
            sysstat \
            tiptop \
            util-linux \
        --nodocs --setopt install_weak_deps=False \
    && dnf clean all -y