FROM ghcr.io/bcachet/containers/dev:latest

RUN sudo dnf install -y \
            bcc \
            bpftrace \
            iproute \
            nicstat \
            numactl \
            sysprof \
            sysstat \
            tiptop \
            util-linux \
        --nodocs --setopt install_weak_deps=False \
    && sudo dnf clean all -y