FROM ghcr.io/bcachet/containers/dev:latest

RUN brew install \
        danielgtaylor/restish/restish \
    || true

RUN sudo dnf install -y \
            go \
        --nodocs --setopt install_weak_deps=False \
    && sudo dnf clean all -y

RUN go install github.com/exoscale/root-api/exoctl@latest
