FROM ghcr.io/bcachet/containers/dev:latest

RUN brew install \
        clojure \
        clojure-lsp \
        borkdude/brew/babashka \
        leiningen \
    || true

RUN mkdir -p ${HOME}/.m2

COPY <<EOF ${HOME}/.m2/setting.xml
<settings>
    <servers>
        <server>
            <id>exoscale</id>
            <username>${env.EXOSCALE_SECRETS_USERNAME}</username>
            <password>${env.EXOSCALE_SECRETS_PASSWORD}</password>
        </server>
    </servers>
</settings>
EOF
