FROM registry.fedoraproject.org/fedora-toolbox:41

RUN dnf install -y \
    curl \
    git \
    direnv \
    eza \
    fd-find \
    file \
    fzf \
    jq \
    just \
    libicu \
    neovim \
    nodejs \
    npm \
    opensc \
    openssh-clients \
    procps-ng \
    ripgrep \
    yq \
    --nodocs --setopt install_weak_deps=False \
    && dnf clean all -y

RUN dnf group install -y 'development-tools' \
    --nodocs --setopt install_weak_deps=False \
    && dnf clean all -y

# Install final user
RUN useradd -m -s /bin/bash -u 1000 bertrand \
    && echo 'bertrand ALL=(ALL) NOPASSWD:ALL' >>/etc/sudoers
RUN mkdir -p /home/linuxbrew/.linuxbrew/bin/ && chown -R bertrand:bertrand /home/linuxbrew/.linuxbrew/
USER bertrand

# Install Brew
ADD --chmod=0755 https://raw.githubusercontent.com/Homebrew/install/master/install.sh /tmp/install.sh
RUN NONINTERACTIVE=1 /tmp/install.sh
ENV PATH=$PATH:/home/linuxbrew/.linuxbrew/bin/

RUN brew install \
    bottom \
    chezmoi \
    lazygit \
    starship

RUN mkdir -p ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
RUN --mount=type=ssh,uid=1000,gid=1000 <<EOF
mkdir -p ~/.local/share/chezmoi && mkdir -p ~/.config/chezmoi
timeout 60 chezmoi init --one-shot --no-tty --no-pager --progress=true git@github.com:bcachet/dotfiles.git
nvim --headless +q || true
EOF
