FROM registry.fedoraproject.org/fedora:40

RUN dnf install -y curl git --nodocs --setopt install_weak_deps=False \
    && dnf clean all -y

# Install Brew
RUN useradd -m -s /bin/bash linuxbrew \
    && echo 'linuxbrew ALL=(ALL) NOPASSWD:ALL' >>/etc/sudoers
USER linuxbrew
RUN curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | bash
ENV PATH=$PATH:/home/linuxbrew/.linuxbrew/bin/
USER root

RUN brew \
        install \
            direnv \
            eza \
            fd \
            fzf \
            jq \
            just \
            ripgrep \
            yq \
    || true
