FROM registry.fedoraproject.org/fedora:40

RUN dnf install -y curl python3 --nodocs --setopt install_weak_deps=False \
    && dnf clean all -y
RUN curl -LsSf https://astral.sh/uv/install.sh | env UV_INSTALL_DIR="/usr/local/bin" sh

