#!/bin/env bash

devpod-cli up \
  "$@" \
  --ide none \
  --ssh-config ~/.ssh/devpod/config \
  --init-env EXOSCALE_ARTIFACTS_USERNAME=$(bw-get --raw "Exoscale maven artifacts" | jq -r .data.username),EXOSCALE_ARTIFACTS_PASSWORD=$(bw-get --raw "Exoscale maven artifacts" | jq -r .data.password) \

