#!/bin/env bash

WORKDIR=$1
SCRIPTDIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

if [ ! -d $WORKDIR/.devcontainer ]; then
  echo "Symlink $SCRIPTDIR/.devcontainer $WORKDIR/.devcontainer"
  ln -s $SCRIPTDIR/.devcontainer $WORKDIR/.devcontainer
fi

source ~/.bashrc.d/bitwarden

devpod-cli up \
  "$@" \
  --ide none \
  --ssh-config ~/.ssh/devpod/config \
  --init-env EXOSCALE_ARTIFACTS_USERNAME=$(bw-get --raw "Exoscale maven artifacts" | jq -r .data.username),EXOSCALE_ARTIFACTS_PASSWORD=$(bw-get --raw "Exoscale maven artifacts" | jq -r .data.password) \

